language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t snehaprem04/docker-react -f DockerFile.dev .
scripts:
  - docker run -e CI=true snehaprem04/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: "Snakey_docker"
    env: "SnakeyDocker-env"
    bucket-name: "elasticbeanstalk-us-east-1-775322342958"
    bucket-path: "Snakey_docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
