language: generic
sudo: required
services:
  - docker
before-install:
<<<<<<< HEAD
  - docker build -t snehaprem/master_sne -f DockerFile.dev .
=======
  - docker build -t snehaprem/master_sne -f dockerfile.dev .
>>>>>>> c9039eeab1b2b78e1872e2eba06b9d2f367a179d
scripts:
  - docker run -e CI=true sehaprem/master_sne npm run test
