language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t snehaprem04/docker-react -f DockerFile.dev .
scripts:
  - docker run -e CI=true snehaprem04/docker-react npm run test
